Feature/generate pdfs
filiperochalopes/sistema-evolucao-medica pull request #3
Opened 2022-10-19 20:41 UTC by Ckk3

ALL WORKING
aih sus - all working
prescricao medica - all working
relatorio de alta -all working
solicitacao de exames - all working
apac - all working
ficha internamento - all working

how to run tests:
pytest /app/app/graphql/mutations/pdfs/tests/

2022-10-21 11:13 UTC, filiperochalopes requested changes
Os testes serão executados bem como o código após essas verificações de sintaxe, grato.

2022-10-21 11:13 UTC, filiperochalopes commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +    global_functions.write_newpdf(output, "./graphql/mutations/pdfs/aih_sus_teste.pdf")
Pelo que vejo ela está criando um pdf físico, o que não é útil para nós que queremos que o pdf apareça na aba e depois suma e não fique arquivado em disco. O interessante seria gerar um [Base64](https://stackoverflow.com/questions/208894/how-to-base64-encode-a-pdf-file-in-python) pois deverá ser resposta de uma mutation, como a própria pasta onde se encontra diz. O código não está com [estrutura de mutation](https://ariadnegraphql.org/docs/mutations.html), seria possível colocá-las nessa forma?

2022-10-21 11:13 UTC, filiperochalopes commented on flaskapp/app/graphql/mutations/pdfs/pdf_apac.py
> +
Os comentários feitos em `pdf_aih_sus` servem para todas as funções semelhantes.

2022-10-21 11:13 UTC, filiperochalopes commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +if __name__ == "__main__":
Não entendi essa parte no final, parece algum tipo de teste, mas não estariam os testes na pasta `tests`?

2022-10-21 11:13 UTC, filiperochalopes commented on flaskapp/app/graphql/mutations/pdfs/pdf_prescricao_medica.py
> +template_directory = "./graphql/mutations/pdfs/pdfs_templates/two_pages_precricao_medica_template.pdf"
Os templates devem ficar em pasta a isso destinado, sugiro `app/assets/pdf_templates`

2022-10-21 11:13 UTC, filiperochalopes commented on flaskapp/app/graphql/resolvers.py
> +
Se quiser ver exemplo de mutations prontas e da arquitetura de pastas mais avançadas pode identificar na branch `feature/graphql-api`, lá temos também a pasta assets.  

![image](https://user-images.githubusercontent.com/34348097/197182783-3bbb3e01-0100-4c7a-b71b-1edfa4949b18.png)

2022-10-21 21:56 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/global_functions.py
> +        if lenMin <= len(text) <= lenMax:
Alterado com sucesso

2022-10-21 21:56 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/global_functions.py
> +def add_morelines_text(can:canvas.Canvas, text:str, initial_pos:tuple, decrease_ypos:int, campName:str, lenMax:int, charPerLines:int, maxLinesAmount:int=None, nullable:bool=False, lenMin:int=0, inter
alteracao feita

2022-10-21 21:57 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/global_functions.py
> +def add_document_cns_cpf_rg(can:canvas.Canvas, document:dict, campName:str, square_size:tuple=(9,9), pos_cpf:tuple=None, pos_cns:tuple=None, pos_rg:tuple=None, pos_square_cpf:tuple=None, pos_square_c
alteracao feita

2022-10-21 22:05 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/global_functions.py
> +        if nullable:
"já que já estão expressas na expressão dos argumentos da função quando da sua declaração, isso já faz com que seja deflagrado erro em caso de tipo diferente do referido."
Eu também imaginei que sim, porém dava pra enviar variáveis de tipo diferente daquele especificado pela função, estou pesquisando agora e aparentemente eu tenho que especificar o tipo da saída da função para elas funcionarem. Vou testar

2022-10-21 22:17 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/global_functions.py
> +        if nullable:
Acabei de confirmar, os typehints nas funções são só isso, dicas, eles não cobram que o tipo seja igual ao que a função pede, isso é mais pra documentação e o desenvolvedor ver msm, eu vou utilizar uma verificação com uma função mesmo e vou adicionar em todos

2022-10-21 22:42 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +def fill_pdf_aih_sus(establishment_solitc_name:str, establishment_solitc_cnes:int, establishment_exec_name:str, establishment_exec_cnes:int, patient_name:str, patient_cns:int, patient_birthday:dateti
Adicionei typehints em todas as funções com o retorno correto

2022-10-21 23:02 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +def fill_pdf_aih_sus(establishment_solitc_name:str, establishment_solitc_cnes:int, establishment_exec_name:str, establishment_exec_cnes:int, patient_name:str, patient_cns:int, patient_birthday:dateti
concluido com sucesso

2022-10-21 23:06 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/global_functions.py
> +def isRGvalid(rg:int) -> bool:
Concluido com sucesso

2022-10-21 23:37 UTC, Ckk3 commented on .gitignore
> +flaskapp/app/graphql/mutations/pdfs/pythrun.py
Resovlido todas essas alterações
os pdfs_templates se encontram na pasta assets/pdfs_templates
o arquivo pythrun.py foi removido 
e os pdfs criados durante testes estão na pasta tests/pdfs_created_files_test

2022-10-21 23:38 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +    global_functions.write_newpdf(output, "./graphql/mutations/pdfs/aih_sus_teste.pdf")
O PDF fisico é criado somente em ambiente de testes, quando o arquivo .py é executado unicamente e não importado por outro programa

2022-10-21 23:39 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +    global_functions.write_newpdf(output, "./graphql/mutations/pdfs/aih_sus_teste.pdf")
Vou efetuar a mudança do return da função para base64

2022-10-21 23:40 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +if __name__ == "__main__":
É a geração do pdf para arquivo, a fim de fazer testes e reparos, esse código não é executado quando é importado

2022-10-21 23:40 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_prescricao_medica.py
> +template_directory = "./graphql/mutations/pdfs/pdfs_templates/two_pages_precricao_medica_template.pdf"
RESOLVIDO
os pdfs_templates agora se encontram na pasta assets/pdfs_templates

2022-10-21 23:42 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +font_directory = "./graphql/mutations/pdfs/Roboto-Mono.ttf"
Resovlido todas essas alterações
os pdfs_templates se encontram na pasta assets/pdfs_templates

2022-10-21 23:56 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_exam_request.py
> +            decreaseYpos = 280
Resolvido.
DecreaseYPOS
DecreasXPOS 
CHAR_PER_LINES
e outras variaveis foram alteradas para contantes

2022-10-22 03:06 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +template_directory = "./graphql/mutations/pdfs/pdfs_templates/aih_sus.pdf"
Tive dificuldades com isso, adicionei a variável, o comando __all__ e nada funcionou

2022-10-22 03:06 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +template_directory = "./graphql/mutations/pdfs/pdfs_templates/aih_sus.pdf"
Assim que terminar os outros eu detalho esse problema

2022-10-22 03:06 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +# Doing the import this way only when is called by antoher file (like pytest)
Tive dificuldades com esse import tambem, vou te enviar detalhes

2022-10-24 23:20 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_apac.py
> +
Retirado esses comentarios

2022-10-24 23:43 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +template_directory = "./graphql/mutations/pdfs/pdfs_templates/aih_sus.pdf"
nao consegui coloca no __init__ pq dava problema de improt circular, então criei um arquivo chamado contants.py com esses valores

2022-10-25 00:58 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +    global_functions.write_newpdf(output, "./graphql/mutations/pdfs/aih_sus_teste.pdf")
mudança feita, agora todas as funções irão gerar um pdf e o retorna encodado em base64

2022-10-25 01:11 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/pdf_aih_sus.py
> +# Doing the import this way only when is called by antoher file (like pytest)
Esse bloco foi removido

2022-10-29 05:27 UTC, Ckk3 commented on flaskapp/app/graphql/mutations/pdfs/global_functions.py
> +        if nullable:
Função criada e implementada em pdf functions

2022-12-08 23:29 UTC, merged